with-expecter: True
packages:
  github.com/fkrhykal/quickbid-account/internal/data:
    interfaces:
      ExecutorManager:
      TxExecutor:
  github.com/fkrhykal/quickbid-account/internal/credential:
    interfaces:
      PasswordHasher:
      PasswordVerifier:
      CredentialTokenCreator:
      UserCredentialRetriever:
filename: 'mock_{{.InterfaceName}}.go'
dir: '{{.InterfaceDir}}'
mockname: 'Mock{{.InterfaceName}}'
outpkg: '{{.PackageName}}'
inpackage: True
