// Code generated by mockery v2.51.1. DO NOT EDIT.

package data

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockExecutorManager is an autogenerated mock type for the ExecutorManager type
type MockExecutorManager[T interface{}] struct {
	mock.Mock
}

type MockExecutorManager_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockExecutorManager[T]) EXPECT() *MockExecutorManager_Expecter[T] {
	return &MockExecutorManager_Expecter[T]{mock: &_m.Mock}
}

// Executor provides a mock function with no fields
func (_m *MockExecutorManager[T]) Executor() T {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Executor")
	}

	var r0 T
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}

// MockExecutorManager_Executor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Executor'
type MockExecutorManager_Executor_Call[T interface{}] struct {
	*mock.Call
}

// Executor is a helper method to define mock.On call
func (_e *MockExecutorManager_Expecter[T]) Executor() *MockExecutorManager_Executor_Call[T] {
	return &MockExecutorManager_Executor_Call[T]{Call: _e.mock.On("Executor")}
}

func (_c *MockExecutorManager_Executor_Call[T]) Run(run func()) *MockExecutorManager_Executor_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutorManager_Executor_Call[T]) Return(_a0 T) *MockExecutorManager_Executor_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutorManager_Executor_Call[T]) RunAndReturn(run func() T) *MockExecutorManager_Executor_Call[T] {
	_c.Call.Return(run)
	return _c
}

// TxExecutor provides a mock function with given fields: ctx
func (_m *MockExecutorManager[T]) TxExecutor(ctx context.Context) (TxExecutor[T], error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TxExecutor")
	}

	var r0 TxExecutor[T]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (TxExecutor[T], error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) TxExecutor[T]); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TxExecutor[T])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutorManager_TxExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxExecutor'
type MockExecutorManager_TxExecutor_Call[T interface{}] struct {
	*mock.Call
}

// TxExecutor is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExecutorManager_Expecter[T]) TxExecutor(ctx interface{}) *MockExecutorManager_TxExecutor_Call[T] {
	return &MockExecutorManager_TxExecutor_Call[T]{Call: _e.mock.On("TxExecutor", ctx)}
}

func (_c *MockExecutorManager_TxExecutor_Call[T]) Run(run func(ctx context.Context)) *MockExecutorManager_TxExecutor_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExecutorManager_TxExecutor_Call[T]) Return(_a0 TxExecutor[T], _a1 error) *MockExecutorManager_TxExecutor_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutorManager_TxExecutor_Call[T]) RunAndReturn(run func(context.Context) (TxExecutor[T], error)) *MockExecutorManager_TxExecutor_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutorManager creates a new instance of MockExecutorManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutorManager[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutorManager[T] {
	mock := &MockExecutorManager[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
